### ISSUE TITLE
No feedback when Gorgon loses connection

### ISSUE THREAD

**Issue by cam-woloshyn** [nulogy/gcloud#1]
Occasionally, Gorgon doesn't load the environment and seems to hang indefinitely (though sometimes it returns a 503 after a long delay.) 
Killing and restarting Gorgon seems to resolve the issue.
Is it possible to get faster feedback?

**Comment by arturopie** [comment]
This seems to be a connection issue. Have your computer lost connection after starting gorgon?

**Comment by ecbrodie** [comment]
@arturopie @cam-woloshyn if this is no longer an issue, then we should close this. Feel free to create a new issue or comment with specific error information, if applicable.

**Comment by arturopie** [comment]
This is an issue in Gorgon, not gcloud. I'll close it
